import { Roles } from 'src/common/enums';

export interface SeedProvider {
    user: { email: string; name: string };
    provider: {
        displayName: string;
        serviceCategories: string[];
        specializationTags: string[];
        serviceAreas: string[];
        homeSector: string;
        homeCity: string;
        homeLat: number;
        homeLng: number;
        experienceYears: number;
        rating: number;
        reviewCount: number;
        onTimePercent: number;
        cancelRate: number;
        completedJobs30d: number;
        baseVisitFee: number;
    };
    role: Roles;
}

const SECTORS = [
    'G-13',
    'G-11',
    'G-10',
    'G-9',
    'F-11',
    'F-10',
    'F-8',
    'F-7',
    'I-8',
    'I-10',
    'E-11',
];

const PROVIDER_DATA = [
    {
        name: 'Ali Khan',
        business: 'Ali Khan AC Services',
        home: 'G-13',
        spec: ['inverter', 'split'],
        gen: 8,
        rating: 4.8,
        on: 0.96,
        cancel: 0.012,
        fee: 1500,
    },
    {
        name: 'Bilal Ahmed',
        business: 'Bilal AC Repair',
        home: 'G-13',
        spec: ['generalist'],
        gen: 5,
        rating: 4.6,
        on: 0.92,
        cancel: 0.037,
        fee: 1400,
    },
    {
        name: 'Kaif Hussain',
        business: 'Kaif Cooling Co.',
        home: 'G-11',
        spec: ['split', 'budget'],
        gen: 6,
        rating: 4.7,
        on: 0.9,
        cancel: 0.022,
        fee: 1200,
    },
    {
        name: 'Hamza Riaz',
        business: 'Hamza Tech',
        home: 'F-11',
        spec: ['generalist'],
        gen: 4,
        rating: 4.3,
        on: 0.85,
        cancel: 0.06,
        fee: 1350,
    },
    {
        name: 'Usman Sheikh',
        business: 'CoolCare Islamabad',
        home: 'F-10',
        spec: ['inverter', 'premium'],
        gen: 10,
        rating: 4.9,
        on: 0.98,
        cancel: 0.008,
        fee: 1800,
    },
    {
        name: 'Faisal Raza',
        business: 'Faisal AC Solutions',
        home: 'I-8',
        spec: ['split', 'window'],
        gen: 7,
        rating: 4.5,
        on: 0.91,
        cancel: 0.025,
        fee: 1450,
    },
    {
        name: 'Tariq Mehmood',
        business: 'Tariq Cooling',
        home: 'G-10',
        spec: ['generalist', 'budget'],
        gen: 3,
        rating: 4.2,
        on: 0.82,
        cancel: 0.07,
        fee: 1100,
    },
    {
        name: 'Imran Aslam',
        business: 'Imran AC Works',
        home: 'F-8',
        spec: ['inverter'],
        gen: 9,
        rating: 4.7,
        on: 0.94,
        cancel: 0.018,
        fee: 1650,
    },
    {
        name: 'Saad Iqbal',
        business: 'Saad Refrigeration',
        home: 'I-10',
        spec: ['commercial', 'central'],
        gen: 12,
        rating: 4.8,
        on: 0.95,
        cancel: 0.015,
        fee: 2200,
    },
    {
        name: 'Yasir Mahmood',
        business: 'Yasir AC Care',
        home: 'F-7',
        spec: ['split', 'premium'],
        gen: 6,
        rating: 4.6,
        on: 0.93,
        cancel: 0.02,
        fee: 1700,
    },
    {
        name: 'Naveed Khan',
        business: 'Naveed Cooling',
        home: 'G-9',
        spec: ['generalist'],
        gen: 5,
        rating: 4.4,
        on: 0.88,
        cancel: 0.04,
        fee: 1300,
    },
    {
        name: 'Asif Mehmood',
        business: 'Asif AC Specialists',
        home: 'E-11',
        spec: ['inverter', 'split'],
        gen: 8,
        rating: 4.7,
        on: 0.94,
        cancel: 0.022,
        fee: 1600,
    },
    {
        name: 'Junaid Khalid',
        business: 'Junaid Tech Services',
        home: 'G-13',
        spec: ['budget'],
        gen: 4,
        rating: 4.1,
        on: 0.8,
        cancel: 0.08,
        fee: 1000,
    },
    {
        name: 'Rashid Anwar',
        business: 'Rashid Cooling Experts',
        home: 'F-11',
        spec: ['inverter', 'premium'],
        gen: 11,
        rating: 4.9,
        on: 0.97,
        cancel: 0.01,
        fee: 1900,
    },
    {
        name: 'Aamir Sohail',
        business: 'Aamir AC Service Center',
        home: 'G-11',
        spec: ['generalist', 'window'],
        gen: 6,
        rating: 4.5,
        on: 0.9,
        cancel: 0.03,
        fee: 1400,
    },
    {
        name: 'Salman Khan',
        business: 'Salman Refrigeration',
        home: 'F-10',
        spec: ['commercial'],
        gen: 9,
        rating: 4.6,
        on: 0.92,
        cancel: 0.025,
        fee: 2000,
    },
    {
        name: 'Zahid Bashir',
        business: 'Zahid Quick Fix',
        home: 'I-8',
        spec: ['generalist', 'budget'],
        gen: 3,
        rating: 4.0,
        on: 0.78,
        cancel: 0.09,
        fee: 1050,
    },
    {
        name: 'Adeel Akhtar',
        business: 'Adeel AC Pros',
        home: 'G-10',
        spec: ['split', 'inverter'],
        gen: 7,
        rating: 4.7,
        on: 0.93,
        cancel: 0.02,
        fee: 1550,
    },
    {
        name: 'Kashif Mehmood',
        business: 'Kashif Cool Care',
        home: 'F-8',
        spec: ['split'],
        gen: 5,
        rating: 4.4,
        on: 0.87,
        cancel: 0.045,
        fee: 1300,
    },
    {
        name: 'Waqas Ali',
        business: 'Waqas AC Solutions',
        home: 'I-10',
        spec: ['inverter', 'premium'],
        gen: 10,
        rating: 4.8,
        on: 0.95,
        cancel: 0.015,
        fee: 1850,
    },
    {
        name: 'Nadeem Hassan',
        business: 'Nadeem Cooling Services',
        home: 'F-7',
        spec: ['generalist'],
        gen: 4,
        rating: 4.3,
        on: 0.85,
        cancel: 0.05,
        fee: 1250,
    },
    {
        name: 'Shahid Iqbal',
        business: 'Shahid AC Works',
        home: 'G-9',
        spec: ['inverter', 'split'],
        gen: 8,
        rating: 4.6,
        on: 0.92,
        cancel: 0.028,
        fee: 1500,
    },
    {
        name: 'Asad Rana',
        business: 'Asad Refrigeration',
        home: 'E-11',
        spec: ['commercial', 'central'],
        gen: 13,
        rating: 4.9,
        on: 0.98,
        cancel: 0.008,
        fee: 2300,
    },
    {
        name: 'Mohsin Raza',
        business: 'Mohsin Cool Tech',
        home: 'G-13',
        spec: ['split', 'window'],
        gen: 5,
        rating: 4.4,
        on: 0.88,
        cancel: 0.04,
        fee: 1350,
    },
    {
        name: 'Ahsan Mahmood',
        business: 'Ahsan AC Specialists',
        home: 'F-11',
        spec: ['inverter'],
        gen: 7,
        rating: 4.7,
        on: 0.93,
        cancel: 0.022,
        fee: 1600,
    },
    {
        name: 'Imtiaz Ahmad',
        business: 'Imtiaz Quick Cool',
        home: 'G-11',
        spec: ['budget', 'generalist'],
        gen: 3,
        rating: 4.1,
        on: 0.8,
        cancel: 0.075,
        fee: 1050,
    },
    {
        name: 'Khurram Shahzad',
        business: 'Khurram AC Experts',
        home: 'F-10',
        spec: ['inverter', 'premium'],
        gen: 11,
        rating: 4.8,
        on: 0.96,
        cancel: 0.012,
        fee: 1900,
    },
    {
        name: 'Zubair Hassan',
        business: 'Zubair Cool Care',
        home: 'I-8',
        spec: ['generalist'],
        gen: 4,
        rating: 4.2,
        on: 0.83,
        cancel: 0.055,
        fee: 1200,
    },
    {
        name: 'Atif Aslam',
        business: 'Atif AC Repair',
        home: 'G-10',
        spec: ['split', 'inverter'],
        gen: 6,
        rating: 4.5,
        on: 0.9,
        cancel: 0.03,
        fee: 1450,
    },
    {
        name: 'Bilal Ahmad Khan',
        business: 'Bilal Refrigeration Hub',
        home: 'F-8',
        spec: ['commercial'],
        gen: 10,
        rating: 4.7,
        on: 0.94,
        cancel: 0.018,
        fee: 2100,
    },
] as const;

function adjacentSectors(home: string): string[] {
    const idx = SECTORS.indexOf(home);
    if (idx < 0) return [home];
    const neighbours = [SECTORS[idx - 1], SECTORS[idx + 1]].filter((s): s is string => Boolean(s));
    return [home, ...neighbours];
}

function emailFor(name: string): string {
    return `${name.toLowerCase().replace(/[^a-z]+/g, '.')}@quickfix.demo`;
}

export const SEED_PROVIDERS: SeedProvider[] = PROVIDER_DATA.map((p) => ({
    role: Roles.PROVIDER,
    user: { email: emailFor(p.name), name: p.name },
    provider: {
        displayName: p.business,
        serviceCategories: ['ac_repair', 'ac_service'],
        specializationTags: [...p.spec],
        serviceAreas: adjacentSectors(p.home),
        homeSector: p.home,
        homeCity: 'Islamabad',
        homeLat: 33.6844,
        homeLng: 73.0479,
        experienceYears: p.gen,
        rating: p.rating,
        reviewCount: 40 + Math.floor(p.rating * 20),
        onTimePercent: p.on,
        cancelRate: p.cancel,
        completedJobs30d: 8 + Math.floor(p.on * 22),
        baseVisitFee: p.fee,
    },
}));

export const SEED_PROVIDER_PASSWORD = 'provider123';
