/**
 * 30-provider mock dataset for QuickFix hackathon demo.
 *
 * All providers are AC technicians based in Islamabad / Rawalpindi.
 * Data is shaped to produce meaningful differentiation across the 8 matching factors:
 *   specialization, on-time rate, distance, cancel rate, review recency,
 *   capacity, budget fit, price per visit.
 *
 * Each entry corresponds to a seed user (role=provider) that must be created
 * first by the ProvidersSeeder before the provider row is inserted.
 */

export interface ProviderSeedEntry {
    // User fields (creates the backing user account)
    email: string;
    name: string;
    passwordHash: string; // pre-hashed: "Password@123"

    // Provider-specific fields
    phone: string;
    location: string;
    serviceCategories: string[];
    specializationTags: string[];
    rating: number;
    onTimePercent: number;
    cancelRate: number;
    totalJobs: number;
    serviceAreaKm: number;
    isAvailable: boolean;
}

// Pre-hashed bcrypt value of "Password@123" at cost 12
const DEFAULT_HASH = '$2b$12$nKL6C.Q9V0ZP4c3YHJlMzeGFZQe5L5fz0AZxBaE9DmSHJeLF9DJO6';

export const PROVIDER_SEED_DATA: ProviderSeedEntry[] = [
    {
        email: 'ali.ac@quickfix.pk',
        name: 'Ali Raza — AC Technician',
        passwordHash: DEFAULT_HASH,
        phone: '+92 300 1234567',
        location: 'G-13/1, Islamabad',
        serviceCategories: ['ac_repair', 'ac_maintenance'],
        specializationTags: ['inverter_ac', 'split_ac', 'lg', 'samsung'],
        rating: 4.8,
        onTimePercent: 0.97,
        cancelRate: 0.01,
        totalJobs: 143,
        serviceAreaKm: 12,
        isAvailable: true,
    },
    {
        email: 'bilal.hvac@quickfix.pk',
        name: 'Bilal Ahmed — HVAC Expert',
        passwordHash: DEFAULT_HASH,
        phone: '+92 301 2345678',
        location: 'G-11/2, Islamabad',
        serviceCategories: ['ac_repair', 'ac_installation', 'ac_maintenance'],
        specializationTags: ['split_ac', 'cassette_ac', 'haier', 'gree'],
        rating: 4.6,
        onTimePercent: 0.93,
        cancelRate: 0.02,
        totalJobs: 89,
        serviceAreaKm: 15,
        isAvailable: true,
    },
    {
        email: 'kamran.cool@quickfix.pk',
        name: 'Kamran Iqbal — Cooling Systems',
        passwordHash: DEFAULT_HASH,
        phone: '+92 302 3456789',
        location: 'F-10/3, Islamabad',
        serviceCategories: ['ac_repair', 'ac_installation'],
        specializationTags: ['window_ac', 'split_ac', 'daikin', 'mitsubishi'],
        rating: 4.7,
        onTimePercent: 0.95,
        cancelRate: 0.015,
        totalJobs: 211,
        serviceAreaKm: 20,
        isAvailable: true,
    },
    {
        email: 'usman.tech@quickfix.pk',
        name: 'Usman Khan — AC Specialist',
        passwordHash: DEFAULT_HASH,
        phone: '+92 303 4567890',
        location: 'I-8/4, Islamabad',
        serviceCategories: ['ac_repair', 'ac_maintenance'],
        specializationTags: ['inverter_ac', 'haier', 'pel', 'orient'],
        rating: 4.4,
        onTimePercent: 0.88,
        cancelRate: 0.04,
        totalJobs: 67,
        serviceAreaKm: 10,
        isAvailable: true,
    },
    {
        email: 'hassan.ac@quickfix.pk',
        name: 'Hassan Mahmood — AC & Refrigeration',
        passwordHash: DEFAULT_HASH,
        phone: '+92 304 5678901',
        location: 'E-11/2, Islamabad',
        serviceCategories: ['ac_repair', 'ac_installation', 'refrigeration'],
        specializationTags: ['split_ac', 'floor_standing', 'gree', 'changhong'],
        rating: 4.5,
        onTimePercent: 0.91,
        cancelRate: 0.03,
        totalJobs: 102,
        serviceAreaKm: 18,
        isAvailable: true,
    },
    {
        email: 'tariq.hvac@quickfix.pk',
        name: 'Tariq Mehmood — HVAC Tech',
        passwordHash: DEFAULT_HASH,
        phone: '+92 305 6789012',
        location: 'Rawalpindi Saddar',
        serviceCategories: ['ac_repair', 'ac_maintenance'],
        specializationTags: ['split_ac', 'inverter_ac', 'samsung', 'lg'],
        rating: 4.3,
        onTimePercent: 0.85,
        cancelRate: 0.06,
        totalJobs: 54,
        serviceAreaKm: 15,
        isAvailable: true,
    },
    {
        email: 'imran.cool@quickfix.pk',
        name: 'Imran Shahid — Cooling Experts',
        passwordHash: DEFAULT_HASH,
        phone: '+92 306 7890123',
        location: 'G-9/3, Islamabad',
        serviceCategories: ['ac_installation', 'ac_maintenance'],
        specializationTags: ['split_ac', 'cassette_ac', 'midea', 'aux'],
        rating: 4.6,
        onTimePercent: 0.94,
        cancelRate: 0.02,
        totalJobs: 78,
        serviceAreaKm: 12,
        isAvailable: true,
    },
    {
        email: 'asad.ac@quickfix.pk',
        name: 'Asad Javed — AC Repair Pro',
        passwordHash: DEFAULT_HASH,
        phone: '+92 307 8901234',
        location: 'H-13, Islamabad',
        serviceCategories: ['ac_repair'],
        specializationTags: ['inverter_ac', 'window_ac', 'haier', 'tcl'],
        rating: 4.2,
        onTimePercent: 0.82,
        cancelRate: 0.07,
        totalJobs: 38,
        serviceAreaKm: 8,
        isAvailable: true,
    },
    {
        email: 'faisal.hvac@quickfix.pk',
        name: 'Faisal Nawaz — Home Climate',
        passwordHash: DEFAULT_HASH,
        phone: '+92 308 9012345',
        location: 'DHA Phase 2, Islamabad',
        serviceCategories: ['ac_repair', 'ac_installation', 'ac_maintenance'],
        specializationTags: ['inverter_ac', 'split_ac', 'daikin', 'carrier'],
        rating: 4.9,
        onTimePercent: 0.98,
        cancelRate: 0.005,
        totalJobs: 287,
        serviceAreaKm: 25,
        isAvailable: true,
    },
    {
        email: 'shahzad.ac@quickfix.pk',
        name: 'Shahzad Ali — AC Technician',
        passwordHash: DEFAULT_HASH,
        phone: '+92 309 0123456',
        location: 'F-7/2, Islamabad',
        serviceCategories: ['ac_repair', 'ac_maintenance'],
        specializationTags: ['split_ac', 'gree', 'haier', 'orient'],
        rating: 4.5,
        onTimePercent: 0.90,
        cancelRate: 0.035,
        totalJobs: 91,
        serviceAreaKm: 14,
        isAvailable: true,
    },
    {
        email: 'nadeem.hvac@quickfix.pk',
        name: 'Nadeem Hussain — HVAC Solutions',
        passwordHash: DEFAULT_HASH,
        phone: '+92 310 1234568',
        location: 'Bahria Town Phase 7, Rawalpindi',
        serviceCategories: ['ac_repair', 'ac_installation'],
        specializationTags: ['floor_standing', 'cassette_ac', 'midea', 'gree'],
        rating: 4.4,
        onTimePercent: 0.87,
        cancelRate: 0.04,
        totalJobs: 63,
        serviceAreaKm: 20,
        isAvailable: true,
    },
    {
        email: 'zubair.cool@quickfix.pk',
        name: 'Zubair Ahmad — Cool Air Services',
        passwordHash: DEFAULT_HASH,
        phone: '+92 311 2345679',
        location: 'I-10/3, Islamabad',
        serviceCategories: ['ac_repair', 'ac_maintenance'],
        specializationTags: ['inverter_ac', 'split_ac', 'pel', 'waves'],
        rating: 4.1,
        onTimePercent: 0.80,
        cancelRate: 0.08,
        totalJobs: 29,
        serviceAreaKm: 10,
        isAvailable: true,
    },
    {
        email: 'waqar.ac@quickfix.pk',
        name: 'Waqar Siddiqui — AC Expert',
        passwordHash: DEFAULT_HASH,
        phone: '+92 312 3456780',
        location: 'G-15/1, Islamabad',
        serviceCategories: ['ac_repair', 'ac_installation', 'ac_maintenance'],
        specializationTags: ['split_ac', 'inverter_ac', 'haier', 'samsung'],
        rating: 4.7,
        onTimePercent: 0.96,
        cancelRate: 0.012,
        totalJobs: 158,
        serviceAreaKm: 16,
        isAvailable: true,
    },
    {
        email: 'rizwan.hvac@quickfix.pk',
        name: 'Rizwan Malik — Climate Control',
        passwordHash: DEFAULT_HASH,
        phone: '+92 313 4567891',
        location: 'Gulberg Green, Islamabad',
        serviceCategories: ['ac_installation', 'ac_maintenance'],
        specializationTags: ['cassette_ac', 'floor_standing', 'daikin', 'trane'],
        rating: 4.8,
        onTimePercent: 0.97,
        cancelRate: 0.008,
        totalJobs: 194,
        serviceAreaKm: 22,
        isAvailable: true,
    },
    {
        email: 'salman.ac@quickfix.pk',
        name: 'Salman Butt — AC Repair & Gas',
        passwordHash: DEFAULT_HASH,
        phone: '+92 314 5678902',
        location: 'Rawalpindi Westridge',
        serviceCategories: ['ac_repair', 'ac_maintenance'],
        specializationTags: ['window_ac', 'split_ac', 'gree', 'tcl'],
        rating: 4.0,
        onTimePercent: 0.78,
        cancelRate: 0.09,
        totalJobs: 22,
        serviceAreaKm: 10,
        isAvailable: true,
    },
    {
        email: 'junaid.cool@quickfix.pk',
        name: 'Junaid Rafiq — Arctic Cool Services',
        passwordHash: DEFAULT_HASH,
        phone: '+92 315 6789013',
        location: 'F-8/2, Islamabad',
        serviceCategories: ['ac_repair', 'ac_installation'],
        specializationTags: ['inverter_ac', 'split_ac', 'haier', 'gree'],
        rating: 4.6,
        onTimePercent: 0.93,
        cancelRate: 0.025,
        totalJobs: 112,
        serviceAreaKm: 14,
        isAvailable: true,
    },
    {
        email: 'tahir.hvac@quickfix.pk',
        name: 'Tahir Qureshi — HVAC Pro',
        passwordHash: DEFAULT_HASH,
        phone: '+92 316 7890124',
        location: 'G-14/4, Islamabad',
        serviceCategories: ['ac_repair', 'ac_maintenance', 'refrigeration'],
        specializationTags: ['split_ac', 'inverter_ac', 'orient', 'pel'],
        rating: 4.3,
        onTimePercent: 0.86,
        cancelRate: 0.045,
        totalJobs: 47,
        serviceAreaKm: 12,
        isAvailable: true,
    },
    {
        email: 'babar.ac@quickfix.pk',
        name: 'Babar Aziz — AC Technician',
        passwordHash: DEFAULT_HASH,
        phone: '+92 317 8901235',
        location: 'I-14/3, Islamabad',
        serviceCategories: ['ac_repair'],
        specializationTags: ['window_ac', 'split_ac', 'waves', 'tcl'],
        rating: 3.9,
        onTimePercent: 0.75,
        cancelRate: 0.10,
        totalJobs: 18,
        serviceAreaKm: 8,
        isAvailable: true,
    },
    {
        email: 'nasir.cool@quickfix.pk',
        name: 'Nasir Mehmood — Cool Tech',
        passwordHash: DEFAULT_HASH,
        phone: '+92 318 9012346',
        location: 'Bahria Town Phase 4, Rawalpindi',
        serviceCategories: ['ac_installation', 'ac_maintenance'],
        specializationTags: ['inverter_ac', 'split_ac', 'midea', 'gree'],
        rating: 4.5,
        onTimePercent: 0.92,
        cancelRate: 0.03,
        totalJobs: 76,
        serviceAreaKm: 18,
        isAvailable: true,
    },
    {
        email: 'adeel.hvac@quickfix.pk',
        name: 'Adeel Farooq — Smart AC Solutions',
        passwordHash: DEFAULT_HASH,
        phone: '+92 319 0123457',
        location: 'G-8/1, Islamabad',
        serviceCategories: ['ac_repair', 'ac_installation', 'ac_maintenance'],
        specializationTags: ['inverter_ac', 'cassette_ac', 'lg', 'daikin'],
        rating: 4.7,
        onTimePercent: 0.95,
        cancelRate: 0.018,
        totalJobs: 167,
        serviceAreaKm: 20,
        isAvailable: true,
    },
    {
        email: 'omar.ac@quickfix.pk',
        name: 'Omar Hamid — AC & Electrical',
        passwordHash: DEFAULT_HASH,
        phone: '+92 320 1234569',
        location: 'PWD Housing Society, Islamabad',
        serviceCategories: ['ac_repair', 'ac_maintenance'],
        specializationTags: ['split_ac', 'inverter_ac', 'haier', 'changhong'],
        rating: 4.4,
        onTimePercent: 0.88,
        cancelRate: 0.038,
        totalJobs: 59,
        serviceAreaKm: 12,
        isAvailable: true,
    },
    {
        email: 'arif.cool@quickfix.pk',
        name: 'Arif Bashir — Comfort Zone AC',
        passwordHash: DEFAULT_HASH,
        phone: '+92 321 2345670',
        location: 'F-11/3, Islamabad',
        serviceCategories: ['ac_repair', 'ac_installation'],
        specializationTags: ['split_ac', 'floor_standing', 'samsung', 'carrier'],
        rating: 4.6,
        onTimePercent: 0.94,
        cancelRate: 0.022,
        totalJobs: 134,
        serviceAreaKm: 16,
        isAvailable: true,
    },
    {
        email: 'danish.hvac@quickfix.pk',
        name: 'Danish Rashid — Freeze Tech',
        passwordHash: DEFAULT_HASH,
        phone: '+92 322 3456781',
        location: 'Rawalpindi Chaklala',
        serviceCategories: ['ac_repair', 'ac_maintenance'],
        specializationTags: ['window_ac', 'split_ac', 'tcl', 'gree'],
        rating: 4.2,
        onTimePercent: 0.83,
        cancelRate: 0.06,
        totalJobs: 41,
        serviceAreaKm: 12,
        isAvailable: true,
    },
    {
        email: 'aamir.ac@quickfix.pk',
        name: 'Aamir Sultan — Premier AC Services',
        passwordHash: DEFAULT_HASH,
        phone: '+92 323 4567892',
        location: 'Sector B, DHA Phase 1, Islamabad',
        serviceCategories: ['ac_repair', 'ac_installation', 'ac_maintenance'],
        specializationTags: ['inverter_ac', 'split_ac', 'daikin', 'mitsubishi', 'carrier'],
        rating: 4.9,
        onTimePercent: 0.99,
        cancelRate: 0.003,
        totalJobs: 312,
        serviceAreaKm: 30,
        isAvailable: true,
    },
    {
        email: 'hamza.cool@quickfix.pk',
        name: 'Hamza Riaz — Ice Cool Tech',
        passwordHash: DEFAULT_HASH,
        phone: '+92 324 5678903',
        location: 'G-10/2, Islamabad',
        serviceCategories: ['ac_repair', 'ac_maintenance'],
        specializationTags: ['split_ac', 'inverter_ac', 'haier', 'orient'],
        rating: 4.5,
        onTimePercent: 0.90,
        cancelRate: 0.032,
        totalJobs: 83,
        serviceAreaKm: 14,
        isAvailable: true,
    },
    {
        email: 'shahid.hvac@quickfix.pk',
        name: 'Shahid Pervaiz — Cool Breeze AC',
        passwordHash: DEFAULT_HASH,
        phone: '+92 325 6789014',
        location: 'E-7/3, Islamabad',
        serviceCategories: ['ac_installation', 'ac_maintenance'],
        specializationTags: ['inverter_ac', 'cassette_ac', 'gree', 'midea'],
        rating: 4.6,
        onTimePercent: 0.93,
        cancelRate: 0.025,
        totalJobs: 99,
        serviceAreaKm: 16,
        isAvailable: true,
    },
    {
        email: 'majid.ac@quickfix.pk',
        name: 'Majid Khan — AC Repair Master',
        passwordHash: DEFAULT_HASH,
        phone: '+92 326 7890125',
        location: 'Koral Town, Islamabad',
        serviceCategories: ['ac_repair'],
        specializationTags: ['split_ac', 'window_ac', 'pel', 'waves'],
        rating: 4.1,
        onTimePercent: 0.79,
        cancelRate: 0.085,
        totalJobs: 25,
        serviceAreaKm: 10,
        isAvailable: true,
    },
    {
        email: 'umer.cool@quickfix.pk',
        name: 'Umer Farooq — Cold Air Pro',
        passwordHash: DEFAULT_HASH,
        phone: '+92 327 8901236',
        location: 'I-16/4, Islamabad',
        serviceCategories: ['ac_repair', 'ac_installation'],
        specializationTags: ['inverter_ac', 'split_ac', 'haier', 'samsung'],
        rating: 4.4,
        onTimePercent: 0.89,
        cancelRate: 0.04,
        totalJobs: 71,
        serviceAreaKm: 14,
        isAvailable: true,
    },
    {
        email: 'rehan.hvac@quickfix.pk',
        name: 'Rehan Zafar — Chill Zone HVAC',
        passwordHash: DEFAULT_HASH,
        phone: '+92 328 9012347',
        location: 'Rawalpindi Khayaban-e-Sir Syed',
        serviceCategories: ['ac_repair', 'ac_maintenance', 'refrigeration'],
        specializationTags: ['split_ac', 'floor_standing', 'gree', 'carrier'],
        rating: 4.5,
        onTimePercent: 0.91,
        cancelRate: 0.028,
        totalJobs: 118,
        serviceAreaKm: 18,
        isAvailable: true,
    },
    {
        email: 'mohsin.ac@quickfix.pk',
        name: 'Mohsin Ali — Arctic Services',
        passwordHash: DEFAULT_HASH,
        phone: '+92 329 0123458',
        location: 'Sector F, CDA, Islamabad',
        serviceCategories: ['ac_repair', 'ac_installation', 'ac_maintenance'],
        specializationTags: ['inverter_ac', 'split_ac', 'lg', 'daikin', 'haier'],
        rating: 4.8,
        onTimePercent: 0.97,
        cancelRate: 0.01,
        totalJobs: 245,
        serviceAreaKm: 22,
        isAvailable: true,
    },
];
